import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    productName: "Blue T-Shirt",
    productShortDescription: "Lorem Ipsum has been the dummy text",
    productLongDescription: "Lorem Ipsum has been the dummy text Lorem Ipsum has been the dummy text",
    trendingText: "Trend",
    categoryName: "men",
    soldBy: "Amazon",
    rating: 4.4,
    salePrice: 899,
    originalPrice: 999,
    discountPercent: 10,
    closeActive: false,
    wishlisted: false,
    imagePath: "/assets/product.jpg",
  },
  {
    _id: uuid(),
    productName: "Blue T-Shirt",
    productShortDescription: "Lorem Ipsum has been the dummy text",
    productLongDescription: "",
    trendingText: "New",
    categoryName: "men",
    soldBy: "Amazon",
    rating: 4.4,
    salePrice: 899,
    originalPrice: 999,
    discountPercent: 10,
    closeActive: false,
    wishlisted: false,
    imagePath: "/assets/product.jpg",
  },
  {
    _id: uuid(),
    productName: "Blue T-Shirt",
    productShortDescription: "Lorem Ipsum has been the dummy text",
    productLongDescription: "",
    trendingText: "New",
    categoryName: "men",
    soldBy: "Amazon",
    rating: 4.4,
    salePrice: 899,
    originalPrice: 999,
    discountPercent: 10,
    closeActive: false,
    wishlisted: false,
    imagePath: "/assets/product.jpg",
  },
  {
    _id: uuid(),
    productName: "Blue T-Shirt",
    productShortDescription: "Lorem Ipsum has been the dummy text",
    productLongDescription: "",
    trendingText: "New",
    categoryName: "men",
    soldBy: "Amazon",
    rating: 4.4,
    salePrice: 899,
    originalPrice: 999,
    discountPercent: 10,
    closeActive: false,
    wishlisted: false,
    imagePath: "/assets/product.jpg",
  },
  {
    _id: uuid(),
    productName: "Blue T-Shirt",
    productShortDescription: "Lorem Ipsum has been the dummy text",
    productLongDescription: "",
    trendingText: "",
    categoryName: "men",
    soldBy: "Amazon",
    rating: 4.4,
    salePrice: 899,
    originalPrice: 999,
    discountPercent: 10,
    closeActive: false,
    wishlisted: false,
    imagePath: "/assets/product.jpg",
  },
  {
    _id: uuid(),
    productName: "Blue T-Shirt",
    productShortDescription: "Lorem Ipsum has been the dummy text",
    productLongDescription: "",
    trendingText: "",
    categoryName: "men",
    soldBy: "Amazon",
    rating: 4.4,
    salePrice: 899,
    originalPrice: 999,
    discountPercent: 10,
    closeActive: false,
    wishlisted: false,
    imagePath: "/assets/product.jpg",
  }
];