import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    productName: "Blue T-Shirt",
    productShortDescription: "Lorem Ipsum has been the dummy text",
    productLongDescription: "Lorem Ipsum has been the dummy text Lorem Ipsum has been the dummy text",
    trendingText: "Trend",
    categoryName: "men",
    soldBy: "Amazon",
    rating: 5,
    salePrice: 990,
    originalPrice: 1100,
    discountPercent: 10,
    closeActive: false,
    wishlisted: false,
    imagePath: "/assets/product.jpg",
  },
  {
    _id: uuid(),
    productName: "Rayban Sunglasses",
    productShortDescription: "Lorem Ipsum has been the dummy text",
    productLongDescription: "Lorem Ipsum has been the dummy text Lorem Ipsum has been the dummy text",
    trendingText: "New",
    categoryName: "men",
    soldBy: "Amazon",
    rating: 4,
    salePrice: 1955,
    originalPrice: 2300,
    discountPercent: 15,
    closeActive: false,
    wishlisted: false,
    imagePath: "/assets/sunglasses.jpg",
  },
  {
    _id: uuid(),
    productName: "Puma Shoes",
    productShortDescription: "Lorem Ipsum has been the dummy text",
    productLongDescription: "Lorem Ipsum has been the dummy text Lorem Ipsum has been the dummy text",
    trendingText: "New",
    categoryName: "men",
    soldBy: "Amazon",
    rating: 5,
    salePrice: 1360,
    originalPrice: 1700,
    discountPercent: 20,
    closeActive: false,
    wishlisted: false,
    imagePath: "/assets/shoes.jpg",
  },
  {
    _id: uuid(),
    productName: "Heels",
    productShortDescription: "Lorem Ipsum has been the dummy text",
    productLongDescription: "Lorem Ipsum has been the dummy text Lorem Ipsum has been the dummy text",
    trendingText: "",
    categoryName: "women",
    soldBy: "Amazon",
    rating: 3,
    salePrice: 759,
    originalPrice: 799,
    discountPercent: 5,
    closeActive: false,
    wishlisted: false,
    imagePath: "/assets/heels.jpg",
  },
  {
    _id: uuid(),
    productName: "Coffee Maker",
    productShortDescription: "Lorem Ipsum has been the dummy text",
    productLongDescription: "Lorem Ipsum has been the dummy text Lorem Ipsum has been the dummy text",
    trendingText: "New",
    categoryName: "electronics",
    soldBy: "Amazon",
    rating: 4,
    salePrice: 495,
    originalPrice: 550,
    discountPercent: 10,
    closeActive: false,
    wishlisted: false,
    imagePath: "/assets/coffee_maker.jpg",
  },
  {
    _id: uuid(),
    productName: "Cleaner",
    productShortDescription: "Lorem Ipsum has been the dummy text",
    productLongDescription: "Lorem Ipsum has been the dummy text Lorem Ipsum has been the dummy text",
    trendingText: "",
    categoryName: "decor",
    soldBy: "Amazon",
    rating: 1,
    salePrice: 360,
    originalPrice: 600,
    discountPercent: 40,
    closeActive: false,
    wishlisted: false,
    imagePath: "/assets/cleaner.jpg",
  },
  {
    _id: uuid(),
    productName: "Skin Creme",
    productShortDescription: "Lorem Ipsum has been the dummy text",
    productLongDescription: "Lorem Ipsum has been the dummy text Lorem Ipsum has been the dummy text",
    trendingText: "New",
    categoryName: "women",
    soldBy: "Amazon",
    rating: 4,
    salePrice: 3150,
    originalPrice: 3500,
    discountPercent: 10,
    closeActive: false,
    wishlisted: false,
    imagePath: "/assets/skin.jpg",
  },
  {
    _id: uuid(),
    productName: "Decoration Frame",
    productShortDescription: "Lorem Ipsum has been the dummy text",
    productLongDescription: "Lorem Ipsum has been the dummy text Lorem Ipsum has been the dummy text",
    trendingText: "New",
    categoryName: "decor",
    soldBy: "Amazon",
    rating: 5,
    salePrice: 810,
    originalPrice: 899,
    discountPercent: 10,
    closeActive: false,
    wishlisted: false,
    imagePath: "/assets/frame.jpg",
  },
];